name: Feature Request
description: File a feature request
labels: ["enhancement"]
title: "[Feature Request]:"

body:
  - type: checkboxes
    id: existingcheck
    attributes:
      label: Do you need to file a feature request?
      description: Please help us manage our time by avoiding duplicates and common feature request with the steps below.
      options:
        - label: I have searched the existing feature request and this feature request is not already filed.
        - label: I believe this is a legitimate feature request, not just a question or bug.
  - type: textarea
    id: feature_request_description
    attributes:
      label: Feature Request Description
      description: A clear and concise description of the feature request you would like.
      placeholder: What does this feature request add or improve?
  - type: dropdown
    id: module
    attributes:
      label: Related Module
      description: Which module would this feature affect?
      options:
        - Dashboard
        - Knowledge Base Management
        - Smart Solver
        - Question Generator
        - Deep Research
        - Co-Writer
        - Notebook
        - Guided Learning
        - Idea Generation
        - API/Backend
        - Frontend/Web
        - Other
    validations:
      required: true
  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe the problem this feature would solve or the use case it would enable.
      placeholder: What problem does this feature solve?
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Any additional information, mockups, or examples
