name: Question
description: Ask a general question
labels: ["question"]
title: "[Question]:"

body:
  - type: checkboxes
    id: existingcheck
    attributes:
      label: Do you need to ask a question?
      description: Please help us manage our time by avoiding duplicates and common questions with the steps below.
      options:
        - label: I have searched the existing questions and discussions and this question is not already answered.
        - label: I believe this is a legitimate question, not just a bug or feature request.
  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: A clear and concise description of your question.
      placeholder: What is your question?
  - type: dropdown
    id: module
    attributes:
      label: Related Module
      description: Which module is your question related to?
      options:
        - Dashboard
        - Knowledge Base Management
        - Smart Solver
        - Question Generator
        - Deep Research
        - Co-Writer
        - Notebook
        - Guided Learning
        - Idea Generation
        - API/Backend
        - Frontend/Web
        - Installation/Setup
        - General
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Provide any additional context or details that might help us understand your question better.
      placeholder: Add any relevant information here (code snippets, error messages, configuration, etc.)
